apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: kuzzle
    namespace: default
    labels:
      app: kuzzle
      tier: backend
  spec:
    selector:
      app: kuzzle
      tier: backend
    ports:
    - name: api
      port: 7512
      targetPort: 7512

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: kuzzle-node
    namespace: default
    labels:
      app: kuzzle
      tier: backend
  spec:
    selector:
      matchLabels:
        app: kuzzle
        tier: backend
    replicas: 1
    template:
      metadata:
        labels:
          app: kuzzle
          tier: backend
      spec:
        containers:
        - image: kuzzleio/kuzzle
          name: kuzzle
          env:
          - name: NODE_ENV
            value: production
          - name: kuzzle_services__db__client__host
            value: http://elasticsearch:9200
          - name: kuzzle_services__internalCache__node__host
            value: redis
          - name: kuzzle_services__memoryStorage__node__host
            value: redis
          ports:
          - containerPort: 7512
            hostPort: 7512
          resources: {}
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
        restartPolicy: Always
kind: List
metadata: {}
