apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: redis
    namespace: default
    labels:
      app: redis
      tier: cache
  spec:
    selector:
      app: redis
      tier: cache
    ports:
    - port: 6379
      targetPort: 6379

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: redis-node
    namespace: default
    labels:
      app: redis
      tier: cache
  spec:
    selector:
      matchLabels:
        app: redis
        tier: cache
    replicas: 1
    template:
      metadata:
        labels:
          app: redis
          tier: cache
      spec:
        containers:
        - name: redis
          image: redis:3.2
          ports:
          - containerPort: 6379
        restartPolicy: Always

kind: List
metadata: {}
